[project]
name = "bgtorrent-observer"
version = "0.1.0"
description = ""
authors = [
    {name = "Dimitar Popchev",email = "dpopchev@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi (>=0.118.0,<0.119.0)",
    "uvicorn (>=0.37.0,<0.38.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4.2"
pytest-cov = "^7.0.0"
pytest-mock = "^3.15.1"
pytest-datafiles = "^3.0.0"
pytest-datadir = "^1.8.0"
mypy = "^1.18.2"
black = "^25.9.0"
isort = "^6.1.0"
pylint = "^3.3.8"
pylint-junit = "^0.3.5"


[tool.poetry.group.jupyter.dependencies]
jupyterlab-vim = "^4.1.4"
jupyterlab-lsp = "^5.2.0"
jupytext = "^1.17.3"
jupyterlab = "^4.4.9"

